### ISSUE TITLE
Remove <br> tag from 2FA SMS messages

### ISSUE THREAD

**Issue by kcole16** [near/near-contract-helper#215]
### Overview
Looks like there is a stray `<br>` tag added to quite a few of the 2FA SMS messages  (transfers, add key, remove keys).

**Comment by mattlockyer** [comment]
Fixed in https://github.com/near/near-contract-helper/pull/214

**Comment by mattlockyer** [comment]
Just noticed this again but fixed it for text based email/sms here:
https://github.com/near/near-contract-helper/pull/214/commits/55de5d74d6234714d46c7c6d18eeaa437c3b8d77
