### ISSUE TITLE
404 - DNS issue

### ISSUE THREAD

**Issue by Gilgahex** [near/near-contract-helper#316]
![Screenshot_2021-01-26_14-51-15](https://user-images.githubusercontent.com/30332451/105916585-00795300-5fe6-11eb-85ed-a2afda856753.png)

Is your onrender account up to date?

**Comment by vgrichina** [comment]
Up to date address is https://helper.testnet.near.org/

Note that 404 is expected response for `/` here as well, only specific endpoints are supported.
