### ISSUE TITLE
Add tracking of funded account requiring deposits

### ISSUE THREAD

**Issue by MaximusHaximus** [near/near-contract-helper#426]
Closes https://github.com/near/near-wallet/issues/1752 backend

**Update  schema:** `Account`
- Add `fundedAccountNeedsDeposit` (boolean flag) so we can track that we have created a particular account using the funded account flow, and nobody has yet sent any funds to it.

**Update existing endpoint:** `POST /fundedAccount`
- Set `fundedAccountNeedsDeposit` to `true` on the `Account` table record we write.
- Return `requiredUnlockBalance` in success payload for the frontend

**New endpoint:**  `POST /fundedAccount/clearNeedsDeposit`
- Clear the initial funded account balance tag from the account record, but only if the current account balance is greater than the minimum account balance (to avoid abuse)
- Returns `requiredUnlockBalance` in failed payload for the frontend

**New endpoint:** `GET /account/walletState`
- Return JSON object for current **wallet** account state -- this is not for fetching on-chain data about the account, but is specifically for fetching metadata that is relevant to the _wallet_ representation of an account that is backed by an on-chain account :)
- Currently, _just_ the `fundedAccountNeedsDeposit` and `requiredUnlockBalance` values will be returned by this endpoint.  In the future we will likely add other metadata.  e.g. `darkMode: true`, `hidePreviouslyTradedTokens: [...]` etc.

NOTE: Original implementation idea was to track the exact amount of funds the account was created with, but would have required backfilling existing account records to change the value if we changed the funded account amount in the future.  

After talking it over with @stefanopepe, we decided to make this a boolean flag instead, so our comparison logic will always use the _current_ value that we need deposited to consider the account funded.  Making the amount dynamic rather than setting it explicitly per account means that:
- If someone creates an account, doesn't deposit any funds for quite some time, and the amount we require goes _down_ (most likely given the assumption that NEAR tokens will increase in value), then the user can deposit a lower amount and still have the 'lock' removed.  This way if someone creates an account but doesn't fund it for an extended period of time, they aren't forced to send a large $$ value amount of NEAR to fund their account _just because they first created it a long time ago._
- If someone creates an account, doesn't deposit any funds for quite some time, and the amount we require for a deposit goes _up_, the amount they were originally required to send will no longer be enough to remove the lock from the account; they will have to send the _current_ required amount to unlock the account, even though the amount required may have been lower when they first made the account.
- We never need to backfill existing account records to 'fix' an excessively high or low requirement for funding due to changes in the required amount over time.

**Comment by stefanopepe** [comment]
What is the related frontend issue&PR? It may help to keep these two related

**Comment by MaximusHaximus** [comment]
Added link to https://github.com/near/near-wallet/issues/1752 in the description :)
