### ISSUE TITLE
Recent activity disabled?

### ISSUE THREAD

**Issue by kraikov** [near/near-contract-helper#602]
Hello there, our application is using the contract helper to get user activity and as I can see the functionality is disabled.  (https://github.com/near/near-contract-helper/commit/3b6f532dde491f3a9b9a47d982bc8cd4a9ebecda) Why is that? Is there a way we can get notified upfront because our users might have bad UX and/or loss of funds due to such kind of things? We are using https://helper.mainnet.near.org

**Comment by andy-haynes** [comment]
Hi @kraikov, the endpoint has been temporarily disabled for performance issues.

It's important to note that we do not recommend using the wallet's contract helper API as a dependency for any non-wallet service. This API is only intended for consumption by the wallet application and while we cannot prevent users from accessing it, we do not make any guarantees on its availability and do not support third-party usage at this time.

**Comment by kraikov** [comment]
The service we're providing is a wallet. And we need the user activity. What alternatives we have?

**Comment by andy-haynes** [comment]
I'm referring to the official NEAR wallet at wallet.near.org. We have no awareness around who utilizes our open REST API and so again cannot make any guarantees around availability.

We strongly encourage third-party applications to implement their own indexers according to their specific requirements, as we do not offer any dedicated public indexers intended for any kind of production use. More information can be found here: https://near-indexers.io/
