### ISSUE TITLE
Accounts error

### ISSUE THREAD

**Issue by lijixy** [near/near-contract-helper#659]
https://helper.mainnet.near.org/publicKey/ed25519:EKveJ28ocxfHXQEfH42AowPL7HgXHkKp3kmMoSXNjiRF/accounts
Response Not Fund, why?

**Comment by miraclx** [comment]
Looks like https://wallet.testnet.near.org currently hosts the helper at https://testnet-api.kitwallet.app

So it will be https://testnet-api.kitwallet.app/publicKey/ed25519:EKveJ28ocxfHXQEfH42AowPL7HgXHkKp3kmMoSXNjiRF/accounts for you

**Comment by lijixy** [comment]
> Looks like https://wallet.testnet.near.org currently hosts the helper at https://testnet-api.kitwallet.app
> 
> So it will be https://testnet-api.kitwallet.app/publicKey/ed25519:EKveJ28ocxfHXQEfH42AowPL7HgXHkKp3kmMoSXNjiRF/accounts for you

Ths for your help
