### ISSUE TITLE
findAccountsByPublicKey: Change the datasource from ExplorerDB to QueryAPI

### ISSUE THREAD

**Issue by eduohe** [near/near-contract-helper#684]
Indexer for explorer Postgres DB will be deprecated on Apr 30th, the endpoint  [findAccountsByPublicKey](https://github.com/near/near-contract-helper/blob/master/src/middleware/indexer.js#L119)   needs to use the new datasource offered by QueryAPI.

This issue is related to https://github.com/near/queryapi/issues/322

**Comment by pkudinov** [comment]
@eduohe when are we planning to release this to prod? I will change this ticket to "In Review". Please mark as done when this is in production this week
